version: '2.4'
services:
  postgres:
    container_name: postgres
    image: 'skyrabot/postgres:latest'
    networks:
      - skyra
    ports:
      - '5432:5432'
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'

  redis:
    command: 'redis-server --port 8287 --requirepass redis'
    container_name: redis
    image: 'redis:alpine'
    networks:
      - skyra
    ports:
      - '8287:8287'
    restart: always

  skyra:
    build:
      context: ../
    container_name: skyra
    depends_on:
      - redis
      - postgres
    env_file:
      - ../src/.env.development
      - ../src/.env.development.local
    image: 'skyrabot/skyra:latest'
    networks:
      - skyra
    ports:
      - '8282:8282'
      - '7282:7282'
    restart: always
    tty: true

volumes:
  postgres-data:
    external: true

networks:
  skyra:
